---
- name: onboarding users
  hosts: "{{ hosts }}"
  become: yes
  become_method: sudo
  tasks:
    - name: create a test file
      file:
        path: /tmp/acirrustech.test
        state: touch
        owner: centos
        group: centos
        mode: 0600

    - name: install package
      package:
        name: "{{ list }}"
        state: installed
